apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reusable-app.fullname" . }}
  labels:
    {{- include "reusable-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reusable-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "reusable-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "reusable-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "reusable-app.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if or .Values.configMaps.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.configMaps.enabled }}
            - configMapRef:
                name: {{ include "reusable-app.fullname" . }}-config
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ include "reusable-app.fullname" . }}-secret
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
