apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: prod/app
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/app
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/app
        property: JWT_SECRET
